[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.3"

[[constraint]]
  branch = "enhancement/increase-timeout"
  name = "github.com/StuartLox/go-kafka-connect"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
